/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#include <pgmspace.h>

#define SECRET
#define THINGNAME "dispositivo-da-palhoca-93"

const char WIFI_SSID[] = "MNET_CARLOS";
const char WIFI_PASSWORD[] = "elisa0811";
const char AWS_IOT_ENDPOINT[] = "a2dx2ashpy96ot-ats.iot.sa-east-1.amazonaws.com";

// Amazon Root CA 1
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

// Device Certificate
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWjCCAkKgAwIBAgIVAJd+gQF/gZPgMhd5VYy+QQxrDwjjMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yNTAzMzEyMTU3
NTJaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh
dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDkLkRqEBMdrgpJySQC
wkWdRfnTZatQdDQiIQU8uTr0Jb6VDg7fo9zt9VdXk22Y4r0fi/vupK7mioi7+meD
8sNi7+xJtZtM2XINTJ25dzHJZGtwkt5fHwBJgFjAEODaKSChtXcmHPWgFR/B/ctb
nxD9+qkgAw9jFDYQGzVXfJrlwW2cygZIgaELzIe0SOHwx1L9j3KE1Fgl+JIt4IDm
MGmONT/PcmLs6uCQd+Ldi4kPo0M+QXnZyNzYeACsK4AtRBWHI4KjLa0JiIgrDRif
hgSKQgmNHxt4ceLtph4FheZNyU6CwbTAnwW5hi8l/duVvjL2wWJEZ3EoYpDjs/GB
M+BFAgMBAAGjYDBeMB8GA1UdIwQYMBaAFO930y6b98MGTOzETFh3mPjyaEePMB0G
A1UdDgQWBBRvBrDrmrG6zEJLITDV4epjMPsJqjAMBgNVHRMBAf8EAjAAMA4GA1Ud
DwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEAqClreYkC5v9WVeqwxgSV0kz7
uQuGaA6ploQlHUQyZj1n9KLlLHUKpGZZOeHPga0tncCp4ktt74Xn4W2F9WkPABNk
/+Q6F4H2/My879CruVQlw4AK1+aC68JCHd59RwDJnvcqMrcTiS+MuDGCFO33mFT0
od2xGhE83BjtM0mI0goDJo2ryHVzDAch+2oxEYDK1X8txJhCsQhXwlDCnfPnFI7F
IiK85g7QElQl7KhPFaVOaspe2deXT1g7PdK+iK5r0odWPqUWIjqPc+xQvoqWw+7R
o3BmPy7xvCb0pEuW2D5Ey6noUfMCUssiJonblnP66fNPFy4G0SzBsDMxZFagcw==
-----END CERTIFICATE-----
)KEY";

// Device Private Key
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA5C5EahATHa4KSckkAsJFnUX502WrUHQ0IiEFPLk69CW+lQ4O
36Pc7fVXV5NtmOK9H4v77qSu5oqIu/png/LDYu/sSbWbTNlyDUyduXcxyWRrcJLe
Xx8ASYBYwBDg2ikgobV3Jhz1oBUfwf3LW58Q/fqpIAMPYxQ2EBs1V3ya5cFtnMoG
SIGhC8yHtEjh8MdS/Y9yhNRYJfiSLeCA5jBpjjU/z3Ji7OrgkHfi3YuJD6NDPkF5
2cjc2HgArCuALUQVhyOCoy2tCYiIKw0Yn4YEikIJjR8beHHi7aYeBYXmTclOgsG0
wJ8FuYYvJf3blb4y9sFiRGdxKGKQ47PxgTPgRQIDAQABAoIBADR5C1SUs8CsiEMl
lTlpMZcUQ3pAtB/BSUfb7hdjxVHl6Cjg3bzCMwkp1VcXWSnCYpmBmILtriboDr+j
uvBWAGadI+pjb/5BNwAl8VN4PKPCiw6NR8P6HhfJAx/QAdVJhe6KC4dhO37/vJjg
40YDk2XEoeXxrjUrra8QgrjGt9xDqucJDQwm1i9EucpvdrDN8t1JcZOPbPCK9cdG
mwFJWFzkDCCeI+jFhu6SUUv6937Q216RuinuSRnKjCbKK7m6dozGsDgyCKlZZFDr
VxR6Vp6hL+NESEpzdtrDp5cKY4cqVPjNprrkjjmjroXK2K2hMV0NDE77Nfnk2HHR
ePcaa+ECgYEA8nQ/I7/cr/fen02aYQd6H1SaMhi4KeYcmtChsBHOSZjV9cSjOhj7
/rMa+HI+9Jvv3dw2mVkZkf1Flj+w2SJeeLpEO48uZl3Qhtuz2aBAfqr9GPA0d2Rp
uuO6LJaGmNDn5F0dgGkBHE/K9CSs7a7yLVGEzobyqZFfcbsT7M8FatkCgYEA8O3f
bJPkJFLZFOcCMVfWWsIktq480dyX3OVIJ0ZJiODuR3/+L3zsDPUJngbfMn7wj3e7
eIBnw0Dqqq1Twx9hEF7qgXHkl9Mb6DLvujf28VydPiFsbGs1o/MeEETSHAxiA+vg
pkbhacZgRCtvkIUcc78Me557PDLl7v3JgKKQhU0CgYEAw82rvDRThu04JhEnDxtZ
vfm2OaUK/hNvoHvDSI1ourkqejwe0mmhAVYl/uVNAID624LfuUJiyyruyuOO8By4
jOlo92yvvU4gfPjrq2KnE2UF1+ENjipS1PLaxO2fr8Ruslec3rpugi3Sqw7/dUin
HoBKL/x99wGHQjMiaUnbhykCgYBCDfWjnyh9jPlXcb54KMzsNS47p6mlIAXC2lnd
6rdef8zUbZMTEfzl0IjCer/W6Far/ve3If1Q2wt7n+nHJWNHSb6hnsg9l/OexdhU
BeP+aJXz4tYHI52hRZaIf1Xbuslkqdb9v5EtnuXlysLbrKMQWODjQ6Al8Q55Z7tH
OUrGQQKBgArR9pGVV01dp6x6mE7hpZbxE8nNvQTh96PNg1qiKBxKIaExBK7RtNWP
2lEJk7bbnQF2/zboQ2n2EgVaBoYzVAXZORC7XpuUz1bzQfARZ3KbN7dW3kex8zig
OqBi1Z1bXfncIahXJ26jZYPIgdxrDXUE5ruAG3g5uAYoCMCN5WFQ
-----END RSA PRIVATE KEY-----
)KEY";